stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: python
  script:
    - pip install build
    - python -m build
  artifacts:
    paths:
      - dist/

black:
  stage: test
  image: python
  script:
    - pip install black
    - black --check .

pytest:
  stage: test
  image: python
  before_script:
    - pip install dist/flaskriver-*.whl pytest
    - pip install -r tests/requirements.txt
  script:
    - pytest ./tests/test_flaskriver.py
    
deploy:
  stage: deploy
  image: python
  variables:
    TWINE_PASSWORD: $TWINE_TOKEN
    TWINE_USERNAME: __token__
  script:
    - pip install twine
    - python -m twine upload dist/* --verbose --skip-existing
  only:
    - main  

deploy-docs:
  stage: deploy
  when: manual
  image: williamyeh/ansible:alpine3
  before_script:
    - cd ~
    - mkdir .ssh
    - echo -n $UBERSPACE_PRIVATE_KEY > .ssh/private_key
    - echo -n $KNOWN_HOSTS > .ssh/known_hosts 
    - chmod 600 .ssh/private_key
    - cd -
  script:
    - ssh -i ~/.ssh/private_key $UBER_USER@$UBER_HOSTNAME "rm -r ~/html/*" 
    - scp -i ~/.ssh/private_key -r ./docs $UBER_USER@$UBER_HOSTNAME:~/html/ 

