site_name: Flaskriver
site_description: Machine learning for data streams in Python
site_author: Sebastian Wette
site_url: https://flaskriver.ml
copyright: Copyright &copy; 2022

repo_name: sebiwtt/flaskriver
repo_url: https://github.com/sebiwtt/flaskriver
edit_uri: ""

theme:
  name: material
  custom_dir: docs/overrides
  language: en
  palette:
    primary: light green
    accent: lime
  font:
    text: Roboto Mono 
    code: Roboto Mono
  logo: img/logo.svg
  favicon: img/logo.svg
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.indexes

extra:
  analytics:
    provider: google
    property: UA-63302552-3
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/sebiwtt/flaskriver

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
      toc_depth: "1-3"
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - awesome-pages


extra_css:
  - css/style.css
